ch = input("Nhập chuỗi cần mã hóa:")
ch2 = list()

print("Mã thay thế\n1.Mã hóa\n2.Giải mã")
lc = int(input("Nhập lựa chọn:"))
while lc!=0:
    if lc==1:
        #mahoa
        print("*Ma hoa:")
        for i in ch:
            if i == "a":ch2.append("x")
            if i == "b":ch2.append("n")
            if i == "c":ch2.append("y")
            if i == "d":ch2.append("a")
            if i == "e":ch2.append("h")
            if i == "f":ch2.append("p")
            if i == "g":ch2.append("o")
            if i == "h":ch2.append("g")
            if i == "i":ch2.append("z")
            if i == "j":ch2.append("q")
            if i == "k":ch2.append("w")
            if i == "l":ch2.append("b")
            if i == "m":ch2.append("t")
            if i == "n":ch2.append("s")
            if i == "o":ch2.append("f")
            if i == "p":ch2.append("l")
            if i == "q":ch2.append("r")
            if i == "r":ch2.append("c")
            if i == "s":ch2.append("v")
            if i == "t":ch2.append("m")
            if i == "u":ch2.append("u")
            if i == "v":ch2.append("e")
            if i == "w":ch2.append("k")
            if i == "x":ch2.append("j")
            if i == "y":ch2.append("d")
            if i == "z":ch2.append("i")
        break
    if lc==2:
        print("*Giai ma:")
        for i in ch:
            if i == "a":ch2.append("d")
            if i == "b":ch2.append("l")
            if i == "c":ch2.append("r")
            if i == "d":ch2.append("y")
            if i == "e":ch2.append("v")
            if i == "f":ch2.append("o")
            if i == "g":ch2.append("h")
            if i == "h":ch2.append("e")
            if i == "i":ch2.append("z")
            if i == "j":ch2.append("x")
            if i == "k":ch2.append("w")
            if i == "l":ch2.append("p")
            if i == "m":ch2.append("t")
            if i == "n":ch2.append("b")
            if i == "o":ch2.append("g")
            if i == "p":ch2.append("f")
            if i == "q":ch2.append("j")
            if i == "r":ch2.append("q")
            if i == "s":ch2.append("n")
            if i == "t":ch2.append("m")
            if i == "u":ch2.append("u")
            if i == "v":ch2.append("e")
            if i == "w":ch2.append("k")
            if i == "x":ch2.append("z")
            if i == "y":ch2.append("c")
            if i == "z":ch2.append("i")
        break
    lc = int(input("Nhập lựa chọn:"))
for i in ch2:
    print(i, end="")